blueprint:
  name: Motion Lighting Control
  description: Reusable lighting automation for controlling lights and switches based on motion, switches, and scenes.
  domain: automation
  input:
    area:
      name: Area
      description: Area where the automation applies
      selector:
        area: {}
    switches:
      name: Switches
      description: List of switches controlling the lights
      selector:
        entity:
          domain: switch
          multiple: true
    motion_sensor:
      name: Motion Sensor
      description: Motion sensor for triggering lights
      selector:
        entity:
          domain: binary_sensor
    light_state:
      name: Light State Selector
      description: Input selector for light state
      selector:
        entity:
          domain: input_select
    motion_timeout:
      name: Motion Timeout (Seconds)
      description: Time to wait before turning off lights after motion stops
      default: 180
      selector:
        number:
          min: 0
          max: 3600
          step: 1

trigger:
  - platform: state
    entity_id: !input light_state
    to: motion
  - platform: state
    entity_id: !input light_state
    to: "on"
  - platform: state
    entity_id: !input light_state
    to: "off"
  - platform: state
    entity_id: !input motion_sensor
    to: "on"
  - platform: state
    entity_id: !input motion_sensor
    to: "off"

variables:
  area: !input area
  motion_sensor: !input motion_sensor
  switches: !input switches
  light_state: !input light_state
  motion_timeout: !input motion_timeout

action:
  - choose:
      # Motion active: Turn on all switches and lights in the area
      - conditions:
          - condition: state
            entity_id: !input light_state
            state: "motion"
          - condition: state
            entity_id: !input motion_sensor
            state: "on"
        sequence:
          - service: switch.turn_on
            target:
              area_id: !input area
          - service: light.turn_on
            target:
              area_id: !input area

      # No motion detected: Delay and then turn off all switches and lights in the area
      - conditions:
          - condition: state
            entity_id: !input light_state
            state: "motion"
          - condition: state
            entity_id: !input motion_sensor
            state: "off"
        sequence:
          - delay:
              seconds: !input motion_timeout
          - service: switch.turn_off
            target:
              area_id: !input area
          - service: light.turn_off
            target:
              area_id: !input area

      # Light state set to "on": Turn on all switches and lights
      - conditions:
          - condition: state
            entity_id: !input light_state
            state: "on"
        sequence:
          - service: switch.turn_on
            target:
              area_id: !input area
          - service: light.turn_on
            target:
              area_id: !input area

      # Light state set to "off": Turn off all switches and lights
      - conditions:
          - condition: state
            entity_id: !input light_state
            state: "off"
        sequence:
          - service: switch.turn_off
            target:
              area_id: !input area
          - service: light.turn_off
            target:
              area_id: !input area
