blueprint:
  name: Room Lighting Control with IKEA Remotes
  description: Reusable lighting automation for controlling lights and switches based on motion, remotes, and scenes.
  domain: automation
  input:
    area:
      name: Area
      description: Area where the automation applies
      selector:
        area: {}
    switches:
      name: Switches or Remotes
      description: Select switches or remotes controlling the lights
      selector:
        device: {}
    motion_sensor:
      name: Motion Sensor
      description: Motion sensor for triggering lights
      selector:
        entity:
          domain: binary_sensor
    light_state:
      name: Light State Selector
      description: Input selector for light state
      selector:
        entity:
          domain: input_select
    motion_timeout:
      name: Motion Timeout (Seconds)
      description: Time to wait before turning off lights after motion stops
      default: 180
      selector:
        number:
          min: 0
          max: 3600
          step: 1

trigger:
  # Motion sensor triggers
  - platform: state
    entity_id: !input motion_sensor
    to: "on"
  - platform: state
    entity_id: !input motion_sensor
    to: "off"

  # Light state changes
  - platform: state
    entity_id: !input light_state
    to: "motion"
  - platform: state
    entity_id: !input light_state
    to: "on"
  - platform: state
    entity_id: !input light_state
    to: "off"

  # IKEA remotes or other device triggers (e.g., zha_event)
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input switches

variables:
  area: !input area
  motion_sensor: !input motion_sensor
  light_state: !input light_state
  motion_timeout: !input motion_timeout

action:
  - choose:
      # Motion active: Turn on lights and switches
      - conditions:
          - condition: state
            entity_id: !input light_state
            state: "motion"
          - condition: state
            entity_id: !input motion_sensor
            state: "on"
        sequence:
          - service: switch.turn_on
            target:
              area_id: !input area
          - service: light.turn_on
            target:
              area_id: !input area

      # No motion: Wait and turn off lights and switches
      - conditions:
          - condition: state
            entity_id: !input light_state
            state: "motion"
          - condition: state
            entity_id: !input motion_sensor
            state: "off"
        sequence:
          - delay:
              seconds: !input motion_timeout
          - service: switch.turn_off
            target:
              area_id: !input area
          - service: light.turn_off
            target:
              area_id: !input area

      # Light state "on": Turn on lights and switches
      - conditions:
          - condition: state
            entity_id: !input light_state
            state: "on"
        sequence:
          - service: switch.turn_on
            target:
              area_id: !input area
          - service: light.turn_on
            target:
              area_id: !input area

      # Light state "off": Turn off lights and switches
      - conditions:
          - condition: state
            entity_id: !input light_state
            state: "off"
        sequence:
          - service: switch.turn_off
            target:
              area_id: !input area
          - service: light.turn_off
            target:
              area_id: !input area

      # IKEA remote "toggle" command: Switch between on and off
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.command == 'toggle' }}"
        sequence:
          - service: input_select.select_option
            target:
              entity_id: !input light_state
            data:
              option: >
                {% if is_state('input_select.light_state', 'on') %}
                  off
                {% else %}
                  on
                {% endif %}
